
package model.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "LibraryImplService", targetNamespace = "http://library/", wsdlLocation = "http://localhost:8080/library/library?wsdl")
public class LibraryImplService
    extends Service
{

    private final static URL LIBRARYIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException LIBRARYIMPLSERVICE_EXCEPTION;
    private final static QName LIBRARYIMPLSERVICE_QNAME = new QName("http://library/", "LibraryImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/library/library?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        LIBRARYIMPLSERVICE_WSDL_LOCATION = url;
        LIBRARYIMPLSERVICE_EXCEPTION = e;
    }

    public LibraryImplService() {
        super(__getWsdlLocation(), LIBRARYIMPLSERVICE_QNAME);
    }

    public LibraryImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), LIBRARYIMPLSERVICE_QNAME, features);
    }

    public LibraryImplService(URL wsdlLocation) {
        super(wsdlLocation, LIBRARYIMPLSERVICE_QNAME);
    }

    public LibraryImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, LIBRARYIMPLSERVICE_QNAME, features);
    }

    public LibraryImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LibraryImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns LibraryImpl
     */
    @WebEndpoint(name = "LibraryImplPort")
    public LibraryImpl getLibraryImplPort() {
        return super.getPort(new QName("http://library/", "LibraryImplPort"), LibraryImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LibraryImpl
     */
    @WebEndpoint(name = "LibraryImplPort")
    public LibraryImpl getLibraryImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://library/", "LibraryImplPort"), LibraryImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (LIBRARYIMPLSERVICE_EXCEPTION!= null) {
            throw LIBRARYIMPLSERVICE_EXCEPTION;
        }
        return LIBRARYIMPLSERVICE_WSDL_LOCATION;
    }

}
