
package model.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "LibraryImpl", targetNamespace = "http://web/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface LibraryImpl {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "logIn", targetNamespace = "http://web/", className = "model.webservice.LogIn")
    @ResponseWrapper(localName = "logInResponse", targetNamespace = "http://web/", className = "model.webservice.LogInResponse")
    @Action(input = "http://web/LibraryImpl/logInRequest", output = "http://web/LibraryImpl/logInResponse")
    public boolean logIn(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1);

}
